# Generated by Django 4.0.3 on 2022-03-18 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название альбома', max_length=250, verbose_name='Название альбома')),
                ('year', models.IntegerField(help_text='Введите год выпуска альбома', null=True, verbose_name='Год выпуска альбома')),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название аккорда (например Am)', max_length=20, verbose_name='Аккорд')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название исполнителя', max_length=250, verbose_name='Исполнитель')),
                ('sostav', models.CharField(help_text='Введите состав группы (при наличии)', max_length=1000, null=True, verbose_name='Состав группы')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название песни', max_length=250, verbose_name='Название песни')),
                ('album', models.ForeignKey(help_text='Выберите альбом', on_delete=django.db.models.deletion.CASCADE, to='mainapp.album', verbose_name='Альбом')),
            ],
        ),
        migrations.CreateModel(
            name='ContentWithChords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Введите содержание (текст песни с расставленными аккордами', verbose_name='Содержание')),
                ('chords', models.ManyToManyField(help_text='Выберите какие аккорды есть в вашем содержании (например Am, C, F).', to='mainapp.chord', verbose_name='Аккорды')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('song', models.ForeignKey(help_text='Выберите песню', on_delete=django.db.models.deletion.CASCADE, to='mainapp.song', verbose_name='Песня')),
            ],
        ),
        migrations.CreateModel(
            name='ChordVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Описание аккорда, картинка или ссылка', verbose_name='Описание аккорда')),
                ('chord', models.ForeignKey(help_text='Выберите аккорд', on_delete=django.db.models.deletion.CASCADE, to='mainapp.chord', verbose_name='Аккорд')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(help_text='Выберите исполнителя', on_delete=django.db.models.deletion.CASCADE, to='mainapp.singer', verbose_name='Исполнитель'),
        ),
    ]
