# Generated by Django 4.0.3 on 2022-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_singer_sostav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='sostav',
            field=models.CharField(help_text='Введите состав группы (при наличии)', max_length=1000, null=True, verbose_name='Состав группы'),
        ),
    ]
