# Generated by Django 4.0.3 on 2022-03-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_singer_sostav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='sostav',
            field=models.TextField(help_text='Введите состав группы (при наличии)', null=True, verbose_name='Состав группы'),
        ),
    ]
