# Generated by Django 4.0.3 on 2022-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_singer_sostav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, help_text='Введите год выпуска альбома', null=True, verbose_name='Год выпуска альбома'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='sostav',
            field=models.TextField(blank=True, help_text='Введите состав группы (при наличии)', null=True, verbose_name='Состав группы'),
        ),
    ]
