# Generated by Django 4.0.3 on 2022-03-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_album_year_alter_singer_sostav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='sostav',
        ),
    ]
