# Generated by Django 4.0.3 on 2022-04-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentwithchords',
            name='likes',
            field=models.IntegerField(default=0, help_text='Введите кол-во лайков', verbose_name='Лайки'),
        ),
    ]
